[server]
# debug 开发模式，release 生产模式
AppMode = debug
HttpPort = :3000
JwtKey = shue7ewah7672
Issuer = Officer

[database]
Db = mysql
DbHost = localhost
DbPort = 3306
DbUser = root
DbPassWord = root1234
DbName = cant_forget

[airtable]
AirtableToken = patCUyNh1moywRSCK.eaf591a09a435b93498f713b9cd765dbd56161e6cc37920e4de5b5bbb78782f0
AirtableDBId = apphKejSbEvYDZiZG